#!/bin/sh
if [ -e /var/run/streamlink.pid ];then
 /etc/init.d/streamlinksrv stop
fi
if [ `grep -c ARMv7 < /proc/cpuinfo` -eq 0 ]; then
  echo "Unsopported CPU architecture!!! / Niewspierana architektura CPU!!!"
  exit 1
else
  exit 0
fi
