#!/bin/sh
[ -e /usr/lib/enigma2/python/Plugins/Extensions/StreamlinkConfig ] && rm -rf /usr/lib/enigma2/python/Plugins/Extensions/StreamlinkConfig
[ -e /usr/lib/enigma2/python/Plugins/Extensions/StreamLinkConfigurator ] && rm -rf /usr/lib/enigma2/python/Plugins/Extensions/StreamLinkConfigurator

if [ -e /etc/opkg/opkg-j00zka.conf ]; then
  if [ -e /usr/lib/python2.7 ]; then
    echo "Python 2.7 NOT supported anymore removing j00zek repo!!!"
    rm -f /etc/opkg/opkg-j00zka.conf
  else
    sed -i 's;opkg-j00zka/;opkg-j00zka-P3/;' /etc/opkg/opkg-j00zka.conf
  fi
fi

if [ -e /usr/lib/python3.12 ]; then
  exit 0
elif [ -e /usr/lib/python3.11 ]; then
  exit 0
elif [ -e /usr/lib/python3.10 ]; then
  exit 0
elif [ -e /usr/lib/python3.9 ]; then
  exit 0
fi
exit 1
