#!/bin/sh
[ -e /usr/lib/enigma2/python/Plugins/Extensions/StreamlinkConfig ] && rm -rf /usr/lib/enigma2/python/Plugins/Extensions/StreamlinkConfig
[ -e /usr/lib/enigma2/python/Plugins/Extensions/StreamLinkConfigurator ] && rm -rf /usr/lib/enigma2/python/Plugins/Extensions/StreamLinkConfigurator

if [ -e /usr/lib/python3.11 ]; then
  exit 0
elif [ -e /usr/lib/python3.10 ]; then
  exit 0
elif [ -e /usr/lib/python3.9 ]; then
  exit 0
fi
exit 1
