#!/bin/sh
if [ `ps -ef 2>&1 |grep -v grep|grep opkg|grep -c remove` -ge 1 ] || [ `ps -l 2>&1 |grep -v grep|grep opkg|grep -c remove` -ge 1 ];then
  rm -rf /usr/share/kodi/addons/repository.kodiwpigulce.pl.k19 > /dev/null 2>&1
  echo "Repozytorium Kodi w pigułce dla Kodi 19.x odinstalowane"
fi
exit 0
