
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-10T07:35:19+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "89ab021c07cd2100b93023f6222fac28365c4d7c",
 "version": "3.2.0+25.g89ab021.dirty"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
