#!/bin/sh
if [ `ps -ef 2>&1 |grep -v grep|grep opkg|grep -c remove` -ge 1 ] || [ `ps -l 2>&1 |grep -v grep|grep opkg|grep -c remove` -ge 1 ];then
  #czyszczenie ewentualnych pozostalosci, ale tylko, jak ktos wywala calkowicie skorke
  rm -rf /usr/lib/enigma2/python/Plugins/Extensions/HddSleep
fi
exit 0
