#!/bin/sh
if [ -e /etc/opkg/opkg-j00zka.conf ]; then
  if [ -e /usr/lib/python2.7 ]; then
    echo "Python 2.7 NOT supported anymore removing j00zek repo!!!"
    rm -f /etc/opkg/opkg-j00zka.conf
  else
    sed -i 's;opkg-j00zka/;opkg-j00zka-P3/;' /etc/opkg/opkg-j00zka.conf
  fi
fi
