#!/bin/sh
plugBinDir=/usr/lib/enigma2/python/Plugins/Extensions/StreamlinkConfig/bin

pythonType='unknown'
if [ -e /usr/lib/python2.7 ]; then
  pythonType='python2.7'
elif [ -e /usr/lib/python3.9 ]; then
  pythonType='python3.9'
elif [ -e /usr/lib/python3.10 ]; then
  pythonType='python3.10'
fi

if [ -f /usr/sbin/streamlinksrv ] && [ ! -L /usr/sbin/streamlinksrv ];then
  echo
  echo "Wykryto zainstalowaną inną, nie w pełni zgodną, wersję streamlinksrv COŚ MOŻE NIE DZIAŁAĆ!!!"
  echo
else
  ln -sf $plugBinDir/streamlink /usr/sbin/streamlink
  ln -sf $plugBinDir/streamlinksrv /usr/sbin/streamlinksrv
  ln -sf /usr/sbin/streamlinksrv /etc/init.d/streamlinksrv
  ln -sf /usr/sbin/streamlinksrv /etc/rc3.d/S50streamlinksrv
  ln -sf /usr/sbin/streamlinksrv /etc/rc4.d/S50streamlinksrv
  if `grep -q 'osd.language=pl_PL' </etc/enigma2/settings`; then
    echo ""
    echo "streamlinksrv zainstalowany"
    echo ""
  else
    echo ""
    echo "streamlinksrv installed"
    echo ""
  fi
  if [ ! -f /etc/streamlink/config ];then
    mkdir -p pythonType
    cp $plugBinDir/etc_streamlink_config.template /etc/streamlink/config
    if [ -e /usr/lib/enigma2/python/Plugins/SystemPlugins/VTIPanel ];then
      ln -sf $plugBinDir/ffmpeg-4-3-1-armhf-static /usr/bin/ffmpeg-4-3-1-armhf-static
      sed -i 's/^#\(ffmpeg-ffmpeg=\)/\1/' /etc/streamlink/config
    fi
  fi
fi

if [ -e /usr/lib/$pythonType/site-packages/streamlink/jtools.py ] && [ `grep -c 'config.plugins.streamlinksrv.enabled=true' < /etc/enigma2/settings` -gt 0 ];then
  if [ -e /etc/init.d/streamlinksrv ];then
    if [ -e /var/run/streamlink.pid ];then
      /etc/init.d/streamlinksrv restart
    else
      /etc/init.d/streamlinksrv start
    fi
    if [ -e /var/run/streamlink.pid ];then
      if `grep -q 'osd.language=pl_PL' </etc/enigma2/settings`; then
        echo "streamlinksrv uruchomiony"
        echo ""
      else
        echo "streamlinksrv started"
        echo ""
      fi 
    else
      if `grep -q 'osd.language=pl_PL' </etc/enigma2/settings`; then
        echo "BŁĄD uruchamiania streamlinksrv !!!"
        echo ""
      else
        echo "ERROR starting streamlinksrv !!!"
        echo ""
      fi
    fi
  fi
fi
touch '/usr/lib/enigma2/python/Plugins/Extensions/StreamlinkConfig/1stRun'

exit 0
