#!/bin/sh
pythonType='unknown'
if [ -e /usr/lib/python2.7 ]; then
  pythonType='python2.7'
elif [ -e /usr/lib/python3.9 ]; then
  pythonType='python3.9'
elif [ -e /usr/lib/python3.10 ]; then
  pythonType='python3.10'
fi

[ -e /etc/init.d/streamlinksrv ] && [ -e /var/run/streamlink.pid ] && /etc/init.d/streamlinksrv stop
[ -e /etc/init.d/streamlinksrv ] && rm -f /etc/init.d/streamlinksrv
[ -e /etc/rc3.d/S50streamlinksrv ] && rm -f /etc/rc3.d/S50streamlinksrv
[ -e /etc/rc4.d/S50streamlinksrv ] && rm -f /etc/rc4.d/S50streamlinksrv

if [ $pythonType != 'unknown' ];then
  [ -e "/usr/lib/$pythonType/site-packages/streamlink" ] && find -L "/usr/lib/$pythonType/site-packages/streamlink" -name *.py -type l -exec  rm {} +
  [ -e "/usr/lib/$pythonType/site-packages/emukodi" ] && rm -rf "/usr/lib/$pythonType/site-packages/emukodi"
  [ -e "/usr/lib/$pythonType/site-packages/streamlink_cli" ] && rm -rf "/usr/lib/$pythonType/site-packages/streamlink_cli"
fi
exit 0
