#!/bin/sh
/usr/lib/enigma2/python/Plugins/Extensions/StreamlinkConfig/bin/re-initiate.sh
if [ $? -gt 0 ];then
  exit 1
else
  if [ `grep 'config.plugins.streamlinksrv.enabled=' < /etc/enigma2/settings|egrep -c 'true|True'` -gt 0 ];then
    if [ -e /etc/init.d/streamlinksrv ];then
      if [ -e /var/run/streamlink.pid ];then
        /etc/init.d/streamlinksrv restart
      else
        /etc/init.d/streamlinksrv start
      fi
      if [ -e /var/run/streamlink.pid ];then
        if `grep -q 'osd.language=pl_PL' </etc/enigma2/settings`; then
          echo "Serwer streamlinka uruchomiony"
          echo ""
        else
          echo "streamlink server started"
          echo ""
        fi 
      else
        if `grep -q 'osd.language=pl_PL' </etc/enigma2/settings`; then
          echo "BŁĄD uruchamiania serwera streamlink !!!"
          echo ""
        else
          echo "ERROR starting streamlink server !!!"
          echo ""
        fi
      fi
    fi
  else
    if `grep -q 'osd.language=pl_PL' </etc/enigma2/settings`; then
      echo "Aktywuj serwer streamlinka w konfiguratorze"
      echo ""
    else
      echo "Enable streamlink server in Configurator"
      echo ""
    fi
  fi
fi
touch '/usr/lib/enigma2/python/Plugins/Extensions/StreamlinkConfig/1stRun'

exit 0
