#!/bin/sh
if `grep -q 'osd.language=pl_PL' </etc/enigma2/settings`; then
  echo ""
  echo "Wtyczka Volumio zainstalowana. Przeładuj teraz GUI!"
  echo ""
else
  echo ""
  echo "Volumio plugin successfully installed. You should restart GUI!"
  echo ""
fi 
exit 0
