#!/bin/sh
if `ps -ef|grep -v grep|grep opkg|grep remove`;then
  rm -rf /usr/lib/enigma2/python/Plugins/Extensions/AlternativeSoftCamManager/
  if `grep -q 'osd.language=pl_PL' </etc/enigma2/settings`; then
    echo ""
    echo "Wtyczka skasowana. Przeładuj teraz GUI!"
    echo ""
  else
    echo ""
    echo "Plugin removed. You should restart GUI!"
    echo ""
  fi 
fi
exit 0
