#!/bin/sh
skinsDir='/usr/share/enigma2'

[ -e $skinsDir/vfd_skin/Homar ] && rm -rf $skinsDir/vfd_skin/Homar
[ -e $skinsDir/vfd_skin/model.* ] && rm -rf $skinsDir/vfd_skin/model.*

find /usr/lib/enigma2/python/Components/ -iname jOOzek*.py*|while read f; do
  rm -f "$f"
done

#check tuner model
if [ -e /proc/stb/info/vumodel ];then
  model=`cat /proc/stb/info/vumodel`
fi

if [ `echo 'duo4k,solo4k,ultimo4k,uno4kse,duo4kse'|grep -c "$model"` -lt 1 ];then
  echo "tuner not compatible"
  exit 1
fi
