#!/bin/sh
if [ -e /usr/lib/enigma2/python/Plugins/SystemPlugins/Extensions/LCD4linux ]; then
  if [ ! -e /usr/lib/enigma2/python/Plugins/SystemPlugins/VTIPanel ];then
    echo "Korzystasz z LCD4Linux, na własną prośbę prosisz się o kłopoty :P"
  fi
fi
exit 0
