#!/bin/sh
if `grep -q 'osd.language=pl_PL' </etc/enigma2/settings`; then
  echo ""
  echo "Paczka skasowana. Przeładuj teraz GUI!"
  echo ""
else
  echo ""
  echo "Package removed. You should restart GUI!"
  echo ""
fi 
exit 0
